runtime: python37
#api_version: 1
#threadsafe: true
# runtime_config:
#   python_version: 3
# [START handlers]
handlers:
- url: /static
  static_dir: static
#- url: /.*
#  script: main.app
# [END handlers]

#libraries:
#- name: flask
#  version: 0.12
#- name: PIL
#  version: 1.1.7
# - name: ssl
#   version: latest